### PR TITLE
Updated package to work with Umbraco Forms 13

### PR DESCRIPTION
**Pull request by AndyBoot**
Hey Aaron,

I've updated the repo to upgrade compatibility with Umbraco 13. My branch was based on your `umbraco-v10` branch but I realise this may cause issues with this PR. Let me know if you need me to re-raise the PR with an `umbraco-v13` branch from your side to make merging any easier (as long as you're happy with the changes 😉).

### csproj:
- Target Framework: .Net 8
- Updated description, tags, version, repo URL's & release notes
- Updated dependencies

### MailChimpWorkFlowType.cs:
- Resolved breaking changes introduced in Umbraco Forms v13

### README.md
- Updated for version 6 of this package

## TESTING
I've tested this on an active project with successful results.

### CODE REVIEW

**Comment by AaronSadlerUK** [comment]
@AndyBoot I will look to tweak this for multi-targeting so that it will continue to work with older Forms

**Comment by AaronSadlerUK** [comment]
6.0.0 Has been pushed to NuGet and supports both V10 and V13

**Comment by AaronSadlerUK** [comment]
@AndyBoot can you update the PR to target the umbraco-v13 branch please

**Comment by AndyBoot** [comment]
Hey @AaronSadlerUK - nice one, I've updated the branch 👍

**Pull request merged**
